.TH REZOUND 1 "Feb 12 2002"
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
rezound \- Graaphical Audio File editor
.SH DESCRIPTION
\fBReZound\fR Supports reading, editing and writing many audio file formats. Currently supported formats are: Native ReZound, WAVE, AIFF/AIFF-C, NeXT/Sun, Berkeley/IRCAM/CARL, raw, Ogg Vorbis, and MPEG Layer-3,2,1 (mp3). 
.TP
\fBReZound\fR enables Fast editing of Large sound files, Cue positions, Automatic Crossfading, and Ability to Save User notes on supported formats. Recording with Realtime level meters, Time Limit settings, is supported, as well as the ability to Reset the record position and add Cue positions on the fly while recording. Playback of Full, and partial selections with Looping and Cue jumping is also built in. 
.TP
This manual page was written for the Debian distribution because the original program does not have a manual page.
.SH AUTHOR
This manual page was written by Anthony Ventimiglia <anthony@ventimiglia.org>,
for the Debian GNU/Linux system (but may be used by others).
.SH SEE ALSO
The \fBReZound\fR Homepage at \fIhttp://rezound.sourceforge.net\fR
